import os
import json
import requests
from unsloth import FastLanguageModel
# from trl import GRPOTrainer, GRPOConfig

ENV_URL = os.getenv("ENV_URL", "http://localhost:8000")

def try_parse_action(completion: str) -> dict:
    """Attempt to parse the JSON string generated by the local policy."""
    try:
        # Strip code blocks or extra text if any
        if "```json" in completion:
            completion = completion.split("```json")[1].split("```")[0]
        cleaned = completion.strip()
        data = json.loads(cleaned)
        return {
            "action_type": data.get("action_type", "analyze_image"),
            "reasoning": data.get("reasoning", "Fallback"),
            "violation_category": data.get("violation_category", "NONE")
        }
    except Exception:
        return {"action_type": "analyze_image", "reasoning": "Error recovery.", "violation_category": "NONE"}

def interact_with_env(completion: str, task_id: str = "task_3_multimodal") -> float:
    """Pings the local /step endpoint to get the live reward from the environment."""
    try:
        action_payload = try_parse_action(completion)
            
        step_res = requests.post(f"{ENV_URL}/step", json=action_payload)
        if step_res.status_code != 200:
            return 0.0
            
        data = step_res.json()
        reward = data.get("reward", 0.0)
        return reward
    except Exception as e:
        print(f"Env error: {e}")
        return 0.0

def env_reward_func(completions, prompts, **kwargs):
    """
    GRPO reward function.
    `completions` is a list of lists of strings or list of strings depending on trl version.
    """
    rewards = []
    # If completions is a list of generation tokens/strings:
    for comp in completions:
        # Optionally, extract task_id from the 'prompts' if you dynamically generate them
        r = interact_with_env(comp)
        rewards.append(r)
    return rewards

def main():
    print("🚀 Initializing Unsloth GRPO Trainer script.")
    print("This connects directly to the Docker environment running on localhost:8000.")
    
    # ----------------------------------------------------
    # TODO: Initialize your model, tokenizer, and dataset
    # ----------------------------------------------------
    
    from datasets import Dataset
    import torch
    
    max_seq_length = 2048
    lora_rank = 16

    print("Loading model...")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name = "unsloth/Meta-Llama-3.1-8B-Instruct",
        max_seq_length = max_seq_length,
        load_in_4bit = True,
        fast_inference = True, 
        gpu_memory_utilization = 0.6,
    )
    
    print("Applying PEFT/LoRA...")
    model = FastLanguageModel.get_peft_model(
        model,
        r = lora_rank,
        target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        lora_alpha = lora_rank,
        use_gradient_checkpointing = "unsloth",
        random_state = 3407,
    )
    
    # Needs a small dataset to kick off the generation process
    # GRPO samples these 'prompts' and tries to generate text for them
    dummy_data = {
        "prompt": [
            "We have a new ad to review. Look at the json state and evaluate it.",
            "You are a Meta Ad-Policy Moderator. What is your next action?",
            "Please review the provided ad."
        ] * 50
    }
    dataset = Dataset.from_dict(dummy_data)
    
    print("Setting up Trainer...")
    from trl import GRPOConfig, GRPOTrainer
    training_args = GRPOConfig(
        output_dir="outputs_grpo",
        learning_rate=5e-5,
        per_device_train_batch_size=1,
        gradient_accumulation_steps=4,
        max_completion_length=128,
        num_generations=4, # Puts 4 variations of completions out for the same prompt
        logging_steps=1,
        max_prompt_length=256,
    )
    
    trainer = GRPOTrainer(
        model=model,
        reward_funcs=[env_reward_func],
        args=training_args,
        train_dataset=dataset,
    )
    
    print("Starting LIVE training...")
    trainer.train()

if __name__ == "__main__":
    main()
